USE [master]
GO

/****** Object:  Database [Conferensions]    Script Date: 23.01.2016 19:21:21 ******/
CREATE DATABASE [Conferensions]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Conferensions', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Conferensions.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Conferensions_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Conferensions_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Conferensions] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Conferensions].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Conferensions] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Conferensions] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Conferensions] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Conferensions] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Conferensions] SET ARITHABORT OFF 
GO

ALTER DATABASE [Conferensions] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Conferensions] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Conferensions] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Conferensions] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Conferensions] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Conferensions] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Conferensions] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Conferensions] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Conferensions] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Conferensions] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Conferensions] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Conferensions] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Conferensions] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Conferensions] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Conferensions] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Conferensions] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Conferensions] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Conferensions] SET RECOVERY FULL 
GO

ALTER DATABASE [Conferensions] SET  MULTI_USER 
GO

ALTER DATABASE [Conferensions] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Conferensions] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Conferensions] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Conferensions] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Conferensions] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Conferensions] SET  READ_WRITE 
GO

